name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check for dump() and var_dump()
      if: "!contains(github.event.head_commit, '[dump | var_dump]')"
